version: "3.5"
services:
  api:
    container_name: dev_api_songs
    build:
      context: .
      dockerfile: ./compose/dev/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    env_file:
      - ./.env
    depends_on:
      - postgres

  postgres:
    container_name: dev_db_songs
    image: postgres:14-alpine
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - songs_postgres_db:/var/lib/postgresql/data

volumes:
  songs_postgres_db:
