version: "3.8"
services:
  api:
    container_name: dev_api_songs
    restart: always
    build:
      context: .
      dockerfile: ./compose/dev/Dockerfile
    ports:
      - ${PROD_PORT}:8000
    volumes:
      - ./:/usr/src/app
    env_file:
      - ./.env
    depends_on:
      - postgres

  postgres:
    container_name: dev_db_songs
    image: postgres:14-alpine
    restart: always
    env_file:
      - ./.env
    volumes:
      - songs_postgres_db:/var/lib/postgresql/data

volumes:
  songs_postgres_db:
