version: "3.5"
services:
  api:
    container_name: prod_api_songs
    restart: always
    build:
      context: .
      dockerfile: ./compose/dev/Dockerfile
    ports:
      - ${PROD_PORT}:8000
    volumes:
      - ./:/usr/src/app
    env_file:
      - ./.env
    depends_on:
      - postgres

  postgres:
    container_name: prod_db_songs
    image: postgres:14-alpine
    restart: always
    env_file:
      - ./.env
    volumes:
      - prod_songs_postgres_db:/var/lib/postgresql/data

volumes:
  prod_songs_postgres_db:
